version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_subscriber_db
    restart: always
    environment:
      POSTGRES_DB: subscriber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:


